Vagrant.configure(2) do |config|
#  config.vm.box = "debian/jessie64"
  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "apachephp"
  config.vm.provision "shell", path: "install.sh"
 
#  config.vm.network :private_network, ip: "192.168.100.10" # only host
#  config.vm.network :public_network, ip: "192.168.100.20"
#  config.vm.network :public_network,:bridge=>"eth0"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.synced_folder ".","/var/www"
 
#  config.vm.provider "virtualbox" do |vb|
#    vb.name = "apachephp"
#    vb.memory = 1024
#    vb.cpus = 1
#    vb.linked_clone = true
#    vb.gui = true
#  end
end
