$mi_script=<<SCRIPT
mkdir -m 0700 /root/.ssh
cp /vagrant/id_ed25519.pub /root/.ssh/authorized_keys
cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys
SCRIPT
 
Vagrant.configure(2) do |config|
  config.vm.define "centos7" do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "centos7"
    config.vm.network "private_network", ip: "10.0.7.11"
    config.vm.provision "shell", inline: $mi_script
#    config.vm.synced_folder ".", "/vagrant", disabled: true
  end
 
  config.vm.define "jessie64" do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "debianjessie64"
    config.vm.network "private_network", ip: "10.0.7.12"
    config.vm.provision "shell", inline: $mi_script
#    config.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "jessie66" do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "debianjessie66"
    config.vm.network "private_network", ip: "10.0.7.14"
    config.vm.provision "shell", inline: $mi_script
#    config.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "trusty64" do |config|
    config.vm.box = "ubuntu/trusty64" 
    config.vm.hostname = "ubuntutrusty64"
    config.vm.network "private_network", ip: "10.0.7.13"
    config.vm.provision "shell", inline: $mi_script
#    config.vm.synced_folder ".", "/vagrant", disabled: true
  end

end
